=== UKHO/periodic-output-service/UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/XmlSchema/CellPermitExchange.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="CellPermitExchange">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="date"/>
				<xs:element ref="cellkeys"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="cell">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="cellname"/>
				<xs:element ref="edition"/>
				<xs:element ref="permit"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="cellkeys">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="cell" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="cellname">
	</xs:element>
	<xs:element name="date">
	</xs:element>
	<xs:element name="edition">
	</xs:element>
	<xs:element name="permit">
	</xs:element>
</xs:schema>

=== UKHO/periodic-output-service/UKHO.FmEssFssMock.API/UKHO.FmEssFssMock.API/Data/A7FB95F0-B3FF-4EF2-9B76-A74C7D3C3C8F/Permit.xml
<?xml version="1.0" encoding="utf-8"?>
<CellPermitExchange xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation=".\CellPermitExchange.xsd">
  <date>2024-04-01 07:44:41</date>
  <cellkeys>
    <cell>
      <cellname>AU220150</cellname>
      <edition>8</edition>
      <permit>AU22015020240101OJ5LR4WQMDQRYFM8L8J8DCAMJRWRD0LD2BGTCDGCVS60SEJR</permit>
    </cell>
    <cell>
      <cellname>AU5PTL01</cellname>
      <edition>1</edition>
      <permit>AU5PTL0120240101I6ROT7NKCJZT7U0EE03K7DIMERNNDTKFZCG298J3EOI6E8KZ</permit>
    </cell>
	  <cell>
		  <cellname>CA570182</cellname>
		  <edition>3</edition>
		  <permit>CA57018220240101FCLWO4I6ERROPFMIPL7HLZDBLMIX4AX6ORESW3EQD99CKBO4</permit>
	  </cell>
	  <cell>
		  <cellname>CA570226</cellname>
		  <edition>3</edition>
		  <permit>CA57022620240101FZSKJT9LZJPVIB1KVXHK0FEU7M3AKB6VN6C9KP6TX8XWWJD2</permit>
	  </cell>
	  <cell>
		  <cellname>CN484220</cellname>
		  <edition>6</edition>
		  <permit>CN48422020240101AGILJPD0REVLVPB4KVDBK8LHI2P4A5B0V6C9KP6TX0XWWJD2</permit>
	  </cell>
	  <cell>
		  <cellname>GB301910</cellname>
		  <edition>10</edition>
		  <permit>GB301910202401014BRMQKD5SPDIYCPV7NVUPKWESS3CCUKZ7TOE0MK5MKS6T6KC</permit>
	  </cell>
  </cellkeys>
</CellPermitExchange>
